### ISSUE TITLE
EO:Bands in the STAC Item properties

### ISSUE THREAD

**Issue by pomadchin** [stac-extensions/eo#12]
Would it make sense to make the EO extension requirements a bit softer? Or that was done on purpose, and the idea behind it was only to use it as a union?

I.e. for the use case when there are items with a significant number of bands (~100), but all assets related to this item have the same band specs; with the current spec it will force the `eo:bands` duplication across all assets of a particular item.

i.e. to allow smth like that:

```js
{
  "type": "Feature",
  // ...
  "assets": {
    "tiff_0": {
      "href": "http://fancy.tiff",
      "roles": [
        "data"
      ],
      "type": "image/tiff; application=geotiff; profile=cloud-optimized"
    },
    // ...
     "tiff_10": {
      "href": "http://fancy10.tiff",
      "roles": [
        "data"
      ],
      "type": "image/tiff; application=geotiff; profile=cloud-optimized"
    }
  },
  "properties": {
    //...
    "eo:bands": [
      {
        "name": "1",
        "center_wavelength": 0.3659136593
      },
      // ...
      {
        "name": "100",
        "center_wavelength": 0.3659136593
      }
    ]
  }
}

```

**Comment by m-mohr** [comment]
Yes, this was done intentionally, but I'm also not a big fan of the union behavior if **all** assets have the same bands (which is not the case anymore if you add a thumbnail or metadata asset).

**Comment by m-mohr** [comment]
The new RFC for a new "bands" construct will allow this: https://github.com/radiantearth/stac-spec/discussions/1213
