### ISSUE TITLE
Need for short alphabetical id to map common band names

### ISSUE THREAD

**Issue by remtav** [stac-extensions/eo#13]
[Common band names](https://github.com/stac-extensions/eo#common-band-names) are a very interesting sensor-agnostic way to refer to band names and hopefully will become a standard in the eo community. 

To further encourage the use of these common names,  short alphabetical id for each common name could be relevant. Here's a suggested mapping:

| Common Name | Common Name Id | Band Range (μm) | Landsat 5/7 | Landsat 8 | Sentinel 2 | MODIS | NAIP |
| ----------- | --- | --------------- | ----------- | --------- | ---------- | ----- | ---- |
| coastal     | Co | 0.40 - 0.45     |             | 1         | 1          |       |      |
| blue        | B | 0.45 - 0.50     | 1           | 2         | 2          | 3     | 3    |
| green       | G | 0.50 - 0.60     | 2           | 3         | 3          | 4     | 2    |
| red         | R | 0.60 - 0.70     | 3           | 4         | 4          | 1     | 1    |
| yellow      | Y | 0.58 - 0.62     |             |           |            |       |      |
| pan         | P | 0.50 - 0.70     | 8 (*L7 only*) | 8       |            |       |      |
| rededge     | Re | 0.70 - 0.79     |             |           | 5, 6, 7    |       |      |
| nir         | N | 0.75 - 1.00     | 4           |           | 8          | 2     | 4    |
| nir08       | N08 | 0.75 - 0.90     |             | 5         | 8a         |       |      |
| nir09       | N09 | 0.85 - 1.05     |             |           | 9          |       |      |
| cirrus      | Ci | 1.35 - 1.40     |             | 9         | 10         | 26    |      |
| swir16      | S16 | 1.55 - 1.75     | 5           | 6         | 11         | 6     |      |
| swir22      | S22 | 2.10 - 2.30     | 7           | 7         | 12         | 7     |      |
| lwir        | L | 10.5 - 12.5     | 6           |           |            |       |      |
| lwir11      | L11 | 10.5 - 11.5     |             | 10        |            | 31    |      |
| lwir12      | L12 | 11.5 - 12.5     |             | 11        |            | 32    |      |

**Comment by ymoisan** [comment]
This comes in handy when one wants to cram as much information in a file (or variable) name and still keep the name somewhat sort.

**Comment by m-mohr** [comment]
Why would this be needed in the STAC extension specification itself? Can't this easily be mapped in applications?

**Comment by matthewhanson** [comment]
Discussed in STAC sprint

@m-mohr to create draft PR for v2.0 of this extension which will remove eo:bands for compliance with upcoming STAC 1.1 - see https://github.com/radiantearth/stac-spec/pull/1254
