### ISSUE TITLE
New band common names to support PlanetScope PSB.SD

### ISSUE THREAD

**Issue by metasim** [stac-extensions/eo#14]
PlanetScope PSB.SD has two green bands. STAC specification needs common names defined to for identifying these bands.

![image](https://user-images.githubusercontent.com/131013/163203037-42e1084d-8922-45a4-a773-e3b863bfaa07.png)

Source: https://assets.planet.com/docs/Planet_Combined_Imagery_Product_Specs_letter_screen.pdf §2.1, Page 14.

**Comment by emmanuelmathot** [comment]
The addition of new common bands is subject to some criteria

> The criteria for adding new common names is that the approximate location and size appears in multiple instruments. This is clearly the case for all the standard colors, Near IR and the 2 main SWIR atmospheric windows. Narrow bands tend to be too specific and unique.

see https://github.com/radiantearth/stac-spec/pull/1054

**Comment by cholmes** [comment]
Unfortunately I think multiple green bands don't yet clear the bar that @emmanuelmathot pointed that we have. If there is evidence of more sensors that have it then it could be added.

**Comment by metasim** [comment]
@emmanuelmathot @cholmes Is it still the opinion of the STAC community that additional green bands do not meet the criteria for being added to the specification?
