### ISSUE TITLE
missing `description` in json-schema

### ISSUE THREAD

**Issue by vincentsarago** [stac-extensions/eo#16]
https://github.com/stac-extensions/eo/blob/d302b29262f2769c2579ebcac9caa336e75352f5/json-schema/schema.json#L147-L184

there is no `description` in ☝️ while it's seems to be in the spec: https://github.com/stac-extensions/eo#band-object

**Comment by KennSmithDS** [comment]
@matthewhanson @m-mohr @emmanuelmathot @sankichi92 

## Issue Description
I am running into this issue too. The reason for it is the schema specifies no `additionalProperties` are allowed, thus blocking anything outside of `name`, `common_name`, `center_wavelength`, `full_width_half_max `, and `solar_illumination `.

## Source of Issue

```json
"fields": {
   "type": "object",
   "properties": {
      "eo:cloud_cover": {
         "title": "Cloud Cover",
         "type": "number",
         "minimum": 0,
         "maximum": 100
      },
     "eo:bands": {
        "$ref": "#/definitions/bands"
      }
   },
   "patternProperties": {
      "^(?!eo:)": {}
     },
   "additionalProperties": false
```

## Proposed Change
- Remove this line of code from the schema ```"additionalProperties": false```, or...
- Add ```"description": { "title": "Band Description", "type": "string"}```

## Code Fix
#20

**Comment by m-mohr** [comment]
It is correct that description is missing, but what has been written about `additionalProperties` is not correct as it doesn't apply for the content of eo:bands. You can add whatever you want to the bands without any validation complaints...

**Comment by m-mohr** [comment]
Created PR #21 to fix this. Reviews would be welcome.
