### ISSUE TITLE
Add rededge1,2,3 to common names

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/eo#19]
It's a bit weird that the common name `rededge` has 3 bands included for S2, which is not ideal if you try to identify bands based on the common names.
The great repository [Awesome Spectral Indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices#expressions) splits the rededge into 3 parts: Red Edge 1, 2 and 3.
I'd propose to add these three in addition.

**Comment by matthewhanson** [comment]
Discussed in STAC sprint

@emmanuelmathot to create draft PR for v2.0 of this extension which will remove eo:bands for compliance with upcoming STAC 1.1 - see https://github.com/radiantearth/stac-spec/pull/1254
