### ISSUE TITLE
Calculation of eo:cloud_cover

### ISSUE THREAD

**Issue by drnextgis** [stac-extensions/eo#25]
Should the `eo:cloud_cover` percentage be calculated for the entire raster or exclusively for the valid data regions (excluding "nodata" areas)? In the given example, the black regions represent areas not captured by a satellite. It's crucial to determine whether these areas should be factored in when calculating `eo:cloud_cover`, as this could yield markedly different results. If nodata areas are excluded and cloud coverage is computed solely over valid regions, the percentage will approach 100%. Conversely, if nodata areas are included, the percentage will be substantially lower.
![image](https://github.com/stac-extensions/eo/assets/866124/d20ecaac-d22e-4694-a603-844c6b84d79c)

**Comment by matthewhanson** [comment]
@drnextgis The cloud cover should be the percent of the valid data area covered by clouds.  This way it will provide a normalized metric for the clouds, otherwise it could heavily depend on how well an image fits into a north-up rectangle and wouldn't be a great metric for cloud cover.

**Comment by drnextgis** [comment]
@matthewhanson, I appreciate your prompt response! Would it be alright if I leave this ticket unresolved until we provide further clarification in the README file? The current information there isn't very clear:
> Estimate of cloud cover as a percentage (0-100) of the entire scene.
