### ISSUE TITLE
Draft version 2.0 of eo:bands

### ISSUE THREAD

**Issue by emmanuelmathot** [stac-extensions/eo#27]
This issue to track the activities to be done for version 2:

- [x] Adapt eo extension for the version 1.1 of STAC spec and the RFC for bands https://github.com/radiantearth/stac-spec/pull/1254
- [ ] Propose a mapping with [awesome spectral indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices) #19

**Comment by m-mohr** [comment]
Closing in favor of milestones: https://github.com/stac-extensions/eo/milestone/2
