### ISSUE TITLE
More Bands

### ISSUE THREAD

**Issue by samsipe** [stac-extensions/eo#7]
Validating against this schema has made it hard to use WorldView and other multispectral sensors with their `common_name`. Please add more bands or allow numbers after `swir`, `nir`, `lwir`, eg: `swir12` or `swir8`. 

Might consider adding these too? 
https://earth.esa.int/eogateway/missions/worldview-3

**Comment by m-mohr** [comment]
I'm pretty sure we discussed this before, but I think there were good reasons for not making this more open. Can you remember, @matthewhanson ?

**Comment by emmanuelmathot** [comment]
> The criteria for adding new common names is that the approximate location and size appears in multiple instruments. This is clearly the case for all the standard colors, Near IR and the 2 main SWIR atmospheric windows. Narrow bands tend to be too specific and unique.

see https://github.com/radiantearth/stac-spec/pull/1054
