### ISSUE TITLE
Support eo:snow_cover as attribute

### ISSUE THREAD

**Issue by torse** [stac-extensions/eo#8]
EO processors often detect snow cover percentages in addition to cloud cover. Currently these information needs to be stored in custom properties which makes them not systematically discoverable. Therefore it would be good if this can be supported by the extension as an optional property, e.g. `eo:snow_cover`.

**Comment by m-mohr** [comment]
I like that idea. Would you be happy to create a proposal? I think a PR would help us get started.

**Comment by torse** [comment]
Yes, here it is. I kept it simple, let me know if it works for you: https://github.com/stac-extensions/eo/pull/9
